server:
  port: 8080
  servlet.context-path: /ms

management:
  server.port: 9000
  endpoints.web:
    exposure.include: "*"
    # allow to call actuator from Swagger UI running on a different (application) port
    cors:
      allowed-origins: http://localhost:${server.port}
      allowed-methods: "*"
  endpoint.health.show-details: always
  health.defaults.enabled: true

logging:
  level:
    root: info
    org.springframework: error
    mirogaudi.memo: info

spring:
  application.name: memo-service

  jpa:
    generate-ddl: false

    hibernate.ddl-auto: none

    properties:
      hibernate:
        connection.provider_disables_autocommit: true

    open-in-view: false

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./build/db/ms;AUTO_SERVER=TRUE
    username: sa
    password: # empty

    hikari:
      auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

springdoc:
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

# Memo service (ms)
ms:
  # Default memo priority
  memo-priority: SHORT_TERM
