server:
  port: 8080
  servlet.context-path: /ms

spring:
  application.name: memo-service

  jpa:
    # Uncomment to generate DB schema script with Spring Data JPA on startup
    #properties.javax.persistence.schema-generation:
    #  create-source: metadata
    #  scripts:
    #    action: create
    #    create-target: src/main/resources/db/migration/V1__create_schema.sql
    #generate-ddl: true

    hibernate.ddl-auto: validate

    open-in-view: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ms
    username: sa
    password:

  h2.console:
    enabled: true
    path: /h2-console

springdoc.swagger-ui:
  tags-sorter: alpha
  operations-sorter: alpha

# Memo service (ms)
# ms: