server:
  port: 8080
  servlet.context-path: /ms

spring:
  application.name: memo-service

  jpa:
    generate-ddl: false
    open-in-view: false

    hibernate.ddl-auto: none

    properties:
      hibernate.connection.provider_disables_autocommit: true

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms
    username: sa
    password: # empty

    hikari.auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: info

springdoc.swagger-ui:
  tags-sorter: alpha
  operations-sorter: alpha

# Memo service (ms)
ms:
  memo-priority: SHORT_TERM
