server:
  port: 8080
  servlet.context-path: /ms

spring:
  application.name: memo-service

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none

    # anti-pattern: enabled in demo purposes to allow lazy fetching during json mapping
    # on prod: disable it and use DTOs
    open-in-view: true

    properties:
      hibernate.connection.provider_disables_autocommit: true

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms
    username: sa
    password: # empty

    hikari.auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: info

springdoc:
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

# Memo service (ms)
ms:
  memo-priority: SHORT_TERM
