logging:
  level:
    root: info
    org.springframework: warn
    mirogaudi.memo: debug

spring:
  jpa:
    generate-ddl: true

    hibernate.ddl-auto: create-drop

    properties:
      jakarta.persistence.schema-generation:
        create-source: metadata
        scripts:
          action: create
          create-target: build/resources/main/db/create_schema.sql
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms
    username: sa
    password: # empty
