create table label
(
    id   bigint generated by default as identity,
    name varchar(128) not null unique,
    primary key (id)
);

create table memo
(
    created_date timestamp(6)  not null,
    due_date     timestamp(6),
    id           bigint generated by default as identity,
    text         varchar(1024) not null,
    priority     enum ('LONG_TERM','MID_TERM','SHORT_TERM'),
    primary key (id)
);

create table memo_label
(
    label_id bigint not null,
    memo_id  bigint not null,
    primary key (label_id, memo_id)
);

alter table if exists memo_label
    add constraint FKepj07fne5r22mtq39mbx3ctlx
    foreign key (label_id)
    references label;

alter table if exists memo_label
    add constraint FKq8qxsj5uwnv0hthjpiixa2x9b
    foreign key (memo_id)
    references memo;
