create table memo
(
    id           bigint generated by default as identity default on null,
    created_date timestamp    not null,
    due_date     timestamp,
    text         varchar(255) not null,
    primary key (id)
);
