create table label
(
    id   bigint generated by default as identity,
    name varchar(128) not null,
    primary key (id)
);

create table memo
(
    id           bigint generated by default as identity,
    created_date timestamp     not null,
    due_date     timestamp,
    priority     varchar(255),
    text         varchar(1024) not null,
    primary key (id)
);

create table memo_label
(
    memo_id  bigint not null,
    label_id bigint not null,
    primary key (memo_id, label_id)
);

alter table label
    add constraint UK_defh0r2wr6e5g7vu7vanv4pxa unique (name);

alter table memo_label
    add constraint FKepj07fne5r22mtq39mbx3ctlx
        foreign key (label_id)
            references label;

alter table memo_label
    add constraint FKq8qxsj5uwnv0hthjpiixa2x9b
        foreign key (memo_id)
            references memo;
